modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="nword"
version="1.0.0"
displayName="nword"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="maciek, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.nword]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.nword]]
    modId="mcreator_link"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nword]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration